/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject2.views.cd;

import com.mycompany.mavenproject2.database.CDBD;
import com.mycompany.mavenproject2.database.CDSetBD;
import com.mycompany.mavenproject2.database.MusicGenreBD;
import com.mycompany.mavenproject2.database.RecordCompanyBD;
import com.mycompany.mavenproject2.database.RefCDOutletBD;
import com.mycompany.mavenproject2.model.CD;
import com.mycompany.mavenproject2.model.CDSet;
import com.mycompany.mavenproject2.model.MusicGenre;
import com.mycompany.mavenproject2.model.RecordCompany;
import com.mycompany.mavenproject2.model.RefCDOutlet;
import com.mycompany.mavenproject2.util.Util;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joshuansu
 */
public class NuevoCD extends javax.swing.JDialog {

    private final CD MG;
    private List<RecordCompany> listR;
    private List<CDSet> listC;
    private List<MusicGenre> listM;
    private List<RefCDOutlet> listO;

    /**
     * Creates new form NuevoArtista
     *
     * @param parent
     * @param modal
     * @param mg
     */
    public NuevoCD(java.awt.Dialog parent, boolean modal, CD mg) {
        super(parent, modal);
        initComponents();
        try {
            listR = RecordCompanyBD.getInstance().getAllRecordCompany();
            listC = CDSetBD.getInstance().getAllCDSet();
            listM = MusicGenreBD.getInstance().getAllMusiGenre();
            listO = RefCDOutletBD.getInstance().getAllCDOutlet();
            llenarCombo();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        if (mg == null) {
            MG = new CD();
        } else {
            MG = mg;
            llenarDatos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WMGNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numeros = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        companyCode = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaP = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        cantidadCanciones = new javax.swing.JTextField();
        varios = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        generoMusical = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        outlet = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        set = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 40));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));

        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel6.setText("Titulo");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de Reproducciones");

        jLabel2.setText("Compañia Discografica");

        jLabel3.setText("Precio");

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });

        jLabel4.setText("MX");

        jLabel5.setText("Fecha de Publicacion");

        jLabel7.setText("Cantidad de Canciones");

        varios.setText("Varios Artistas");
        varios.setToolTipText("");
        varios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel8.setText("Genero Musical");

        jLabel9.setText("Disponible en");

        jLabel10.setText("Set CD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeros))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaP, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outlet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varios))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(save))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(fechaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(generoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cantidadCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varios)
                    .addComponent(jLabel9)
                    .addComponent(outlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(jButton2))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        guardar();
    }//GEN-LAST:event_saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadCanciones;
    private javax.swing.JComboBox<String> companyCode;
    private org.jdesktop.swingx.JXDatePicker fechaP;
    private javax.swing.JComboBox<String> generoMusical;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeros;
    private javax.swing.JComboBox<String> outlet;
    private javax.swing.JTextField precio;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> set;
    private javax.swing.JCheckBox varios;
    // End of variables declaration//GEN-END:variables

    private void llenarDatos() {
        nombre.setText(MG.getTitle());
        numeros.setText(MG.getTotalPlayingTimes() + "");
        if (MG.getRecordCompanyCode() != null && !MG.getRecordCompanyCode().trim().equals("")) {
            companyCode.setSelectedItem(getNameCompany(MG.getRecordCompanyCode()));
        }

        if (MG.getOutletCode() != null && !MG.getOutletCode().trim().equals("")) {
            outlet.setSelectedItem(MG.getOutletCode());
        }

        if (MG.getMusicGenreCode() != null && !MG.getMusicGenreCode().trim().equals("")) {
            generoMusical.setSelectedItem(MG.getMusicGenreCode());
        }

        if (MG.getCDSetid() != -1) {
            set.setSelectedItem(getNameSet(MG.getCDSetid()));
        }
        precio.setText(MG.getCost());
        fechaP.setDate(Util.getDateFromLocalDate(MG.getDateReleased()));
        cantidadCanciones.setText(MG.getNumberOfTracks() + "");
        varios.setSelected(MG.isVariousArtists());
    }

    private void guardar() {
        if (!nombre.getText().trim().equals("")) {
            MG.setTitle(nombre.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Titulo incompleto");
            return;
        }

        if (Util.isInt(numeros.getText().trim())) {
            MG.setTotalPlayingTimes(Integer.valueOf(numeros.getText().trim()));
        } else {
            JOptionPane.showMessageDialog(this, "Error en cantidad, numero entero porfavor");
            return;
        }

        if (Util.isNumber(precio.getText().trim())) {
            MG.setCost(precio.getText().trim());
        }

        if (Util.isInt(cantidadCanciones.getText().trim())) {
            MG.setNumberOfTracks(Integer.valueOf(numeros.getText().trim()));
        } else {
            JOptionPane.showMessageDialog(this, "Error en cantidad, numero entero porfavor");
            return;
        }

        if (fechaP.getDate() != null) {
            MG.setDateReleased(Util.getLocalDateFromDate(fechaP.getDate()));
        }

        MG.setVariousArtists(varios.isSelected());

        MG.setRecordCompanyCode(getCodeCompany(companyCode.getSelectedItem().toString()));
        MG.setOutletCode(outlet.getSelectedItem().toString());
        MG.setMusicGenreCode(generoMusical.getSelectedItem().toString());
        MG.setCDSetid(getIDSet(set.getSelectedItem().toString()));

        try {
            CDBD.getInstance().saveCD(MG);
            dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void llenarCombo() {
        companyCode.removeAll();
        listR.forEach(c -> {
            companyCode.addItem(c.getName());
        });

        outlet.removeAll();
        listO.forEach(c -> {
            outlet.addItem(c.getCode());
        });

        generoMusical.removeAll();
        listM.forEach(c -> {
            generoMusical.addItem(c.getCode());
        });

        set.removeAll();
        listC.forEach(c -> {
            set.addItem(c.getName());
        });
    }

    private String getCodeCompany(String name) {
        return listR.stream().filter(c -> c.getName().equals(name))
                .findFirst()
                .get()
                .getCode();
    }

    private String getNameCompany(String code) {
        return listR.stream().filter(c -> c.getCode().equals(code))
                .findFirst()
                .get()
                .getName();
    }

    private long getIDSet(String name) {
        return listC.stream().filter(c -> c.getName().equals(name))
                .findFirst()
                .get()
                .getId();
    }

    private String getNameSet(long id) {
        return listC.stream().filter(c -> c.getId() == id)
                .findFirst()
                .get()
                .getName();
    }

}
